# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-added-large-files
        -   id: check-ast
        -   id: check-case-conflict
        -   id: check-json
        -   id: check-vcs-permalinks
        -   id: pretty-format-json
        -   id: check-xml
        -   id: check-yaml
        -   id: mixed-line-ending
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.782
      hooks:
        -   id: mypy
