"""prepare spotifyartist for images

Revision ID: 0401b8fbede9
Revises: 68bfc3ad5986
Create Date: 2020-04-19 21:14:50.711679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0401b8fbede9'
down_revision = '68bfc3ad5986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_artists', sa.Column('good_image', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('spotify_artists', sa.Column('image_override_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotify_artists', 'image_override_name')
    op.drop_column('spotify_artists', 'good_image')
    # ### end Alembic commands ###
