"""add api_key

Revision ID: 11757f587bae
Revises: 1aeed0f68691
Create Date: 2019-08-11 12:34:22.299778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11757f587bae'
down_revision = '1aeed0f68691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_key')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('toodledo_token_json', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('habitica_user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('habitica_api_token', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('dependencies', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priorities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
