"""add api_key

Revision ID: 11757f587bae
Revises: 1aeed0f68691
Create Date: 2019-08-11 12:34:22.299778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11757f587bae'
down_revision = '1aeed0f68691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###
