"""put api response on track model

Revision ID: 1dfe6f097569
Revises: d9c55002c736
Create Date: 2021-01-16 11:56:46.505958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dfe6f097569'
down_revision = 'd9c55002c736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_tracks', sa.Column('api_response', sa.Text(), nullable=True))
    op.drop_column('top_tracks', 'api_response')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_tracks', sa.Column('api_response', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('spotify_tracks', 'api_response')
    # ### end Alembic commands ###
