"""add readwise access token

Revision ID: 24dff3f748d6
Revises: d47c5c6d78db
Create Date: 2020-11-08 11:48:40.391885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24dff3f748d6'
down_revision = 'd47c5c6d78db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('readwise_access_token', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['readwise_access_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'readwise_access_token')
    # ### end Alembic commands ###
