"""add best selling artists

Revision ID: 29afac58afde
Revises: 363e21cc8a59
Create Date: 2020-10-06 16:41:38.813193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29afac58afde'
down_revision = '363e21cc8a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('best_selling_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_uri', sa.String(length=128), nullable=False),
    sa.Column('claimed_sales', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_uri'], ['spotify_artists.uri'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_uri')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('best_selling_artists')
    # ### end Alembic commands ###
