"""add date artist was added

Revision ID: 2c22a1dd13af
Revises: 165a6097b85a
Create Date: 2020-03-14 17:23:28.986030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c22a1dd13af'
down_revision = '165a6097b85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_spotify_artists', sa.Column('date_added', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managed_spotify_artists', 'date_added')
    # ### end Alembic commands ###
