"""artist uri can no longer be unique

Revision ID: 2e6c8a0c4ea5
Revises: 817a51136c54
Create Date: 2021-01-18 19:13:08.139209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6c8a0c4ea5'
down_revision = '817a51136c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('best_selling_artists_artist_uri_key', 'best_selling_artists', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('best_selling_artists_artist_uri_key', 'best_selling_artists', ['artist_uri'])
    # ### end Alembic commands ###
