"""add most recent top track refresh time

Revision ID: 306582a6a98f
Revises: d4beb975ba20
Create Date: 2020-05-17 14:31:53.050173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306582a6a98f'
down_revision = 'd4beb975ba20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_artists', sa.Column('last_top_tracks_refresh', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotify_artists', 'last_top_tracks_refresh')
    # ### end Alembic commands ###
