"""add number of seasons

Revision ID: 363e21cc8a59
Revises: 594b3de426d1
Create Date: 2020-09-29 10:02:27.353364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363e21cc8a59'
down_revision = '594b3de426d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('seasons', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'seasons')
    # ### end Alembic commands ###
