"""cache spotify artist image url

Revision ID: 381609ac24fc
Revises: 8a2ebc919f81
Create Date: 2020-04-23 22:45:40.817492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381609ac24fc'
down_revision = '8a2ebc919f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_artists', sa.Column('spotify_image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotify_artists', 'spotify_image_url')
    # ### end Alembic commands ###
