"""max minutes

Revision ID: 39d4e9812288
Revises: cb8006d9637b
Create Date: 2019-08-30 20:33:58.395780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d4e9812288'
down_revision = 'cb8006d9637b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('maximum_minutes_per_day', sa.Integer(), server_default='120', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'maximum_minutes_per_day')
    # ### end Alembic commands ###
