"""create columns for what used to be in redis

Revision ID: 3f59e50fd925
Revises: 9722139332b6
Create Date: 2020-07-23 22:32:28.701184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f59e50fd925'
down_revision = '9722139332b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cached_trello_data', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_random_play_offset', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_spotify_track', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'users', 'spotify_tracks', ['last_spotify_track'], ['uri'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'last_spotify_track')
    op.drop_column('users', 'last_random_play_offset')
    op.drop_column('users', 'cached_trello_data')
    # ### end Alembic commands ###
