"""add persons, credits

Revision ID: 46cc49df2efd
Revises: daf722ec18f0
Create Date: 2020-07-19 17:54:31.886640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46cc49df2efd'
down_revision = 'daf722ec18f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_persons',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('known_for', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_credits',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('video_id', sa.Text(), nullable=False),
    sa.Column('person_id', sa.Text(), nullable=False),
    sa.Column('character', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['video_persons.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_credits')
    op.drop_table('video_persons')
    # ### end Alembic commands ###
