"""add following flag

Revision ID: 4af7788cc6b1
Revises: be024217bc9f
Create Date: 2020-04-04 15:29:50.809120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af7788cc6b1'
down_revision = 'be024217bc9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_spotify_artists', sa.Column('following', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managed_spotify_artists', 'following')
    # ### end Alembic commands ###
