"""add trello member id for webhooks

Revision ID: 4c12a602c9f4
Revises: 7be2878b34fb
Create Date: 2020-07-26 14:22:51.414079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c12a602c9f4'
down_revision = '7be2878b34fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trello_member_id', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['trello_member_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'trello_member_id')
    # ### end Alembic commands ###
