"""wikipedia page + follow

Revision ID: 5246dd9e99d1
Revises: 697f1a006f5a
Create Date: 2020-12-08 19:14:09.598518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5246dd9e99d1'
down_revision = '697f1a006f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wikipedia_pages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wikipedia_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wikipedia_page_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wikipedia_page_id'], ['wikipedia_pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'wikipedia_page_id', name='_user_id_wikipedia_page_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wikipedia_follows')
    op.drop_table('wikipedia_pages')
    # ### end Alembic commands ###
