"""add rsAnki javascript column

Revision ID: 5de6eee4d895
Revises: 74f7325272e0
Create Date: 2020-04-11 21:56:46.534908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de6eee4d895'
down_revision = '74f7325272e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uses_rsAnki_javascript', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('users', 'api_key',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'api_key',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('users', 'uses_rsAnki_javascript')
    # ### end Alembic commands ###
