"""untappd username column

Revision ID: 6487627f037a
Revises: 5246dd9e99d1
Create Date: 2020-12-12 10:46:29.182224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6487627f037a'
down_revision = '5246dd9e99d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('untappd_username', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['untappd_username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'untappd_username')
    # ### end Alembic commands ###
