"""add legacy guid mapping table

Revision ID: 68bfc3ad5986
Revises: 5de6eee4d895
Create Date: 2020-04-12 00:53:32.521872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bfc3ad5986'
down_revision = '5de6eee4d895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legacy_spotify_track_note_guid_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spotify_track_uri', sa.String(length=128), nullable=False),
    sa.Column('anki_guid', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['spotify_track_uri'], ['spotify_tracks.uri'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'anki_guid', name='_user_id_and_anki_guid'),
    sa.UniqueConstraint('user_id', 'spotify_track_uri', name='_user_id_and_spotify_track_uri')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legacy_spotify_track_note_guid_mappings')
    # ### end Alembic commands ###
