"""add recurrence types

Revision ID: 697f1a006f5a
Revises: 8fa45f6ad32a
Create Date: 2020-11-27 16:58:46.854804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = '697f1a006f5a'
down_revision = '8fa45f6ad32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    recurrence_type = postgresql.ENUM('FROM_COMPLETION_DATE', 'FROM_DUE_DATE', 'NONE', name='recurrence_type')
    recurrence_type.create(op.get_bind())

    op.add_column('tasks', sa.Column('recurrence_type', sa.Enum('FROM_COMPLETION_DATE', 'FROM_DUE_DATE', 'NONE', name='recurrence_type'), server_default='FROM_COMPLETION_DATE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'recurrence_type')

    recurrence_type = postgresql.ENUM('FROM_COMPLETION_DATE', 'FROM_DUE_DATE', 'NONE', name='recurrence_type')
    recurrence_type.drop(op.get_bind())
    # ### end Alembic commands ###
