"""create managed spotify artists table

Revision ID: 772afc03fa3d
Revises: 262f300198bf
Create Date: 2020-03-14 14:15:49.938314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772afc03fa3d'
down_revision = '262f300198bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_spotify_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spotify_artist_uri', sa.String(length=128), nullable=False),
    sa.Column('spotify_artist_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('managed_spotify_artists')
    # ### end Alembic commands ###
