"""second table for legacy mapping

Revision ID: 7b5402e5af3c
Revises: 68bfc3ad5986
Create Date: 2020-04-12 01:52:09.788076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5402e5af3c'
down_revision = '68bfc3ad5986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legacy_model_id_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anki_spotify_track_model_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legacy_model_id_mappings')
    # ### end Alembic commands ###
