"""add feature model

Revision ID: 7b8fb6d93340
Revises: 8f5083f1cf50
Create Date: 2020-08-14 09:14:57.082228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8fb6d93340'
down_revision = '8f5083f1cf50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotify_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_track_uri', sa.String(length=128), nullable=False),
    sa.Column('spotify_artist_uri', sa.String(length=128), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spotify_artist_uri'], ['spotify_artists.uri'], ),
    sa.ForeignKeyConstraint(['spotify_track_uri'], ['spotify_tracks.uri'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_track_uri', 'ordinal'),
    sa.UniqueConstraint('spotify_track_uri', 'spotify_artist_uri')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spotify_features')
    # ### end Alembic commands ###
