"""add foreign key constraint to youtube keys

Revision ID: 7c7a9fb2f886
Revises: 9f7359b9a3d3
Create Date: 2020-07-22 09:56:10.570789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7a9fb2f886'
down_revision = '9f7359b9a3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'videos', 'youtube_videos', ['youtube_trailer_key'], ['key'])
    op.create_foreign_key(None, 'youtube_video_overrides', 'youtube_videos', ['youtube_trailer_key'], ['key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'youtube_video_overrides', type_='foreignkey')
    op.drop_constraint(None, 'videos', type_='foreignkey')
    # ### end Alembic commands ###
