"""make top list more generic

Revision ID: 817a51136c54
Revises: 1dfe6f097569
Create Date: 2021-01-18 18:38:29.295016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817a51136c54'
down_revision = '1dfe6f097569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('best_selling_artists', sa.Column('source', sa.Text(), server_default='https://en.wikipedia.org/wiki/List_of_best-selling_music_artists', nullable=True))
    op.alter_column('best_selling_artists', 'claimed_sales',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('best_selling_artists', 'claimed_sales',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('best_selling_artists', 'source')
    # ### end Alembic commands ###
