"""trello

Revision ID: 83a3d27de55e
Revises: 39d4e9812288
Create Date: 2019-10-18 12:38:18.620251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a3d27de55e'
down_revision = '39d4e9812288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trello_api_access_token', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('trello_api_key', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trello_api_key')
    op.drop_column('users', 'trello_api_access_token')
    # ### end Alembic commands ###
