"""add foreign key and non-null constraint after backfilled

Revision ID: 8a2073751905
Revises: 98bfb39389ff
Create Date: 2020-05-31 18:26:00.183742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2073751905'
down_revision = '98bfb39389ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spotify_tracks', 'spotify_album_uri',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_foreign_key(None, 'spotify_tracks', 'spotify_albums', ['spotify_album_uri'], ['uri'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spotify_tracks', type_='foreignkey')
    op.alter_column('spotify_tracks', 'spotify_album_uri',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
