"""save api response for top track

Revision ID: 8a2ebc919f81
Revises: 8b907b5af7d4
Create Date: 2020-04-21 00:49:00.184037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2ebc919f81'
down_revision = '8b907b5af7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_tracks', sa.Column('api_response', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('top_tracks', 'api_response')
    # ### end Alembic commands ###
