"""add top tracks model

Revision ID: 8b907b5af7d4
Revises: 0401b8fbede9
Create Date: 2020-04-21 00:13:39.671517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b907b5af7d4'
down_revision = '0401b8fbede9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_uri', sa.String(length=128), nullable=False),
    sa.Column('track_uri', sa.String(length=128), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.CheckConstraint('ordinal <= 10'),
    sa.CheckConstraint('ordinal >= 1'),
    sa.ForeignKeyConstraint(['artist_uri'], ['spotify_artists.uri'], ),
    sa.ForeignKeyConstraint(['track_uri'], ['spotify_tracks.uri'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_uri', 'ordinal'),
    sa.UniqueConstraint('artist_uri', 'track_uri')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_tracks')
    # ### end Alembic commands ###
