"""add last refreshed at

Revision ID: 8f5083f1cf50
Revises: f1645c3175ba
Create Date: 2020-08-12 19:48:27.112537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5083f1cf50'
down_revision = 'f1645c3175ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hn_stories', sa.Column('last_refreshed_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hn_stories', 'last_refreshed_at')
    # ### end Alembic commands ###
