"""add album model

Revision ID: 98bfb39389ff
Revises: 306582a6a98f
Create Date: 2020-05-30 15:21:55.656271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bfb39389ff'
down_revision = '306582a6a98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotify_albums',
    sa.Column('uri', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('spotify_artist_uri', sa.String(length=128), nullable=False),
    sa.Column('album_type', sa.String(length=128), nullable=False),
    sa.Column('spotify_image_url', sa.Text(), nullable=True),
    sa.Column('released_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['spotify_artist_uri'], ['spotify_artists.uri'], ),
    sa.PrimaryKeyConstraint('uri')
    )
    op.add_column('spotify_tracks', sa.Column('spotify_album_uri', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotify_tracks', 'spotify_album_uri')
    op.drop_table('spotify_albums')
    # ### end Alembic commands ###
