"""normalize models & track plays

Revision ID: 9b2dd325878b
Revises: d54deb83df4a
Create Date: 2020-03-23 20:16:58.616431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2dd325878b'
down_revision = 'd54deb83df4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotify_artists',
    sa.Column('uri', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('uri')
    )
    op.create_table('spotify_tracks',
    sa.Column('uri', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('spotify_artist_uri', sa.String(length=128), nullable=False),
    sa.Column('duration_milliseconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spotify_artist_uri'], ['spotify_artists.uri'], ),
    sa.PrimaryKeyConstraint('uri')
    )
    op.create_table('spotify_plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spotify_track_uri', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['spotify_track_uri'], ['spotify_tracks.uri'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('managed_spotify_artists', 'spotify_artist_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_spotify_artists', sa.Column('spotify_artist_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'managed_spotify_artists', type_='foreignkey')
    op.drop_table('spotify_plays')
    op.drop_table('spotify_tracks')
    op.drop_table('spotify_artists')
    # ### end Alembic commands ###
