"""task completion add at col

Revision ID: a1654de7c7d1
Revises: fcbfd34e49b5
Create Date: 2019-11-23 20:02:42.596360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1654de7c7d1'
down_revision = 'fcbfd34e49b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_service_task_completions', sa.Column('at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_service_task_completions', 'at')
    # ### end Alembic commands ###
