"""broaden credit to include crew

Revision ID: a68c22349a06
Revises: ff4b69acd073
Create Date: 2020-08-19 09:46:24.192641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68c22349a06'
down_revision = 'ff4b69acd073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_credits', sa.Column('job', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_credits', 'job')
    # ### end Alembic commands ###
