"""create youtube overrides table

Revision ID: bd2d19af16eb
Revises: 1f2c8a628b05
Create Date: 2020-07-21 21:15:23.339056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd2d19af16eb'
down_revision = '1f2c8a628b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_video_overrides',
    sa.Column('video_id', sa.Text(), nullable=False),
    sa.Column('youtube_trailer_key', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_video_overrides')
    # ### end Alembic commands ###
