"""api_key_is_unique

Revision ID: cb8006d9637b
Revises: 11757f587bae
Create Date: 2019-08-11 12:43:09.737835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8006d9637b'
down_revision = '11757f587bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.create_unique_constraint(None, 'users', ['api_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('toodledo_token_json', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('habitica_user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('habitica_api_token', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('dependencies', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priorities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
