"""add ability to specify tag

Revision ID: d0dc9a1b4bb1
Revises: 747670001ada
Create Date: 2020-06-14 12:55:31.049666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0dc9a1b4bb1'
down_revision = '747670001ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_spotify_anki_tag', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_spotify_anki_tag')
    # ### end Alembic commands ###
