"""create reminders based on pushover

Revision ID: d4beb975ba20
Revises: 381609ac24fc
Create Date: 2020-05-16 01:03:22.992982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4beb975ba20'
down_revision = '381609ac24fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('sent_via', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('pushover_user_key', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'users', ['pushover_user_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'pushover_user_key')
    op.drop_table('reminder_notifications')
    op.drop_table('reminders')
    # ### end Alembic commands ###
