"""add original title

Revision ID: daf0305d8ed1
Revises: 29afac58afde
Create Date: 2020-10-16 11:56:34.109483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf0305d8ed1'
down_revision = '29afac58afde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('original_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'original_name')
    # ### end Alembic commands ###
