"""add differentiator for TV or Film

Revision ID: daf722ec18f0
Revises: 9ecc41438e32
Create Date: 2020-07-19 15:55:48.407403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf722ec18f0'
down_revision = '9ecc41438e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('film_or_tv', sa.Text(), server_default='film', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'film_or_tv')
    # ### end Alembic commands ###
