"""start logging tasks from trello

Revision ID: ddad0d4aa2d4
Revises: 43ff73722b3d
Create Date: 2020-08-11 10:55:44.541785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddad0d4aa2d4'
down_revision = '43ff73722b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_logs', sa.Column('task_name', sa.Text(), nullable=True))
    op.alter_column('task_logs', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_logs', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('task_logs', 'task_name')
    # ### end Alembic commands ###
