"""add at to readlog model

Revision ID: ff4b69acd073
Revises: 7b8fb6d93340
Create Date: 2020-08-15 09:22:52.812494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4b69acd073'
down_revision = '7b8fb6d93340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hn_read_logs', sa.Column('at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hn_read_logs', 'at')
    # ### end Alembic commands ###
